### ISSUE TITLE
Can't start flatpak Nuvola from the desktop launcher

### ISSUE THREAD

**Issue by excieve** [tiliado/nuvolaruntime#348]
After some recent update to flatpak distribution I can't start any Nuvola apps using the GNOME 3 desktop launcher. Here's the relevant log for Google Play app:
```
чер 01 11:35:55 frankenstein.home systemd[2209]: Started flatpak-eu.tiliado.NuvolaAppGooglePlayMusic-8426.scope.
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]: unique: 8, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 8430
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]:    unique: 8, success, outsize: 120
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]: unique: 9, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 8430
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]:    unique: 9, success, outsize: 144
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]: unique: 10, opcode: LOOKUP (1), nodeid: 2, insize: 76, pid: 8430
чер 01 11:35:55 frankenstein.home xdg-document-portal[7552]:    unique: 10, success, outsize: 144
чер 01 11:35:55 frankenstein.home eu.tiliado.NuvolaAppGooglePlayMusic.desktop[8426]: execvp True: No such file or directory
```

Here's for the base Nuvola:
```
чер 01 11:40:26 frankenstein.home systemd[2209]: Started flatpak-eu.tiliado.Nuvola-8894.scope.
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]: unique: 11, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 8899
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]:    unique: 11, success, outsize: 120
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]: unique: 12, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 8899
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]:    unique: 12, success, outsize: 144
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]: unique: 13, opcode: LOOKUP (1), nodeid: 2, insize: 58, pid: 8899
чер 01 11:40:26 frankenstein.home xdg-document-portal[7552]:    unique: 13, success, outsize: 144
чер 01 11:40:27 frankenstein.home eu.tiliado.Nuvola.desktop[8894]: execvp nuvolaruntime: No such file or **directory**
```

Looks like something in the `.desktop` files isn't right as launching manually (`flatpak run ...`) works fine.

**Comment by fenryxo** [comment]
Hello @excieve. Thanks for reporting this issue. It should be easy to fix. I'll rebuild packages as soon as I get to my PC.

**Comment by fenryxo** [comment]
It should be now fixed in the stable branch. Could you verify it?

**Comment by excieve** [comment]
@fenryxo Hmm, still having the same error messages. Do I need to do something except `flatpak update`?

**Comment by fenryxo** [comment]
`flatpak update --system && flatpak update --user` (without sudo/root rights) is recommended. Could you verify version? `flatpak run eu.tiliado.Nuvola//stable --version`

**Comment by excieve** [comment]
Updating both system and user flatpaks helped, it works fine now. Thanks!

Checked versions before and after this, apparently it was 4.4.0 before and 4.4.1 after. Wondering why simply running `flatpak update` doesn't seem to be enough?

**Comment by fenryxo** [comment]
flatpak update is confusing. When it is run as root, it probably updates only system flatpaks, and if executed as a regular user, probably only user flatpaks are updated.

**Comment by fenryxo** [comment]
Well, manpage says: "Unless overridden with the --user or the --installation option, this command updates the default system-wide installation."

**Comment by fenryxo** [comment]
Fix released in Nuvola 4.5.

**Comment by bjwest** [comment]
Is there a way to have Nuvola check for updates periodically, to both itself and the plugins?  I keep it open all the time and sleep my computer, only rebooting when there's a system up date that requires it.

**Comment by fenryxo** [comment]
Nuvola doesn't do any update checks. However, GNOME Software updates flatpaks periodically in the background and I think it also shows a notification when an app is updated.
